### PR TITLE
CRL validator dynamically reloads CRLs

### PR DESCRIPTION
**Pull request by dandds**
Trying to clear the third task in [this](https://www.pivotaltracker.com/story/show/158161825) PT story.

In the last PR, I added a cronjob that will periodically update the local copies of the CRLs. In this PR, the Python CRL validator keeps a cache of file checksums for every CRL. If it sees that the relevant CRL has changed when it goes to validate a client cert, it will refresh the whole store. (pyopenssl doesn't give us a way to remove individual CRLs, so we have to rebuild the whole thing.) 

I'm curious what people think of this approach or if there's a better way to accomplish this. Doing a checksum comparison every time might be more work than it's worth, but on the other hand, I don't think we want to reboot the app once a day to reload all the CRLs.

### CODE REVIEW

**Comment by dandds** [comment]
Pushed a small commit to ensure we're downloading the root CRLs, too. (They've actually revoked intermediary certs over time!)

**Comment by jordangov** [comment]
I have no problem with the approach, but we may see that we're reloading all the CRLs every day anyway unless we can find some way to refresh a single list. In that case, we probably don't need this and can just do a cron job overnight to refresh them.

**Comment by ddsdevon** [comment]
@jordangov Do you mean have a cronjob that asks the app to reload them... ? I think the current goal here is that the app autodetects the change in checksum when the local files are updated, so it does not have to be rebooted to get the new versions.

**Comment by jordangov** [comment]
Hmm... is that what we're doing? From Dan's PR description it wasn't clear. I guess I'm referring to this: "I don't think we want to reboot the app once a day to reload all the CRLs"

And my point is... if pyopenssl can't reload one list and has to reload ALL CRLs, then we might end up reloading all CRLs (and rebooting the app) each day anyway, so do we really need the checksum comparison here?

**Comment by dandds** [comment]
@jordangov Devon's understanding is right. The cronjob that refreshes the CRLs on-disk runs independently of the app. This PR allows the app to recreate its store when it detects changes without rebooting; it just rebuilds the SSL X509Store object. Effectively, it probably does mean rebuilding once-a-day, but without a reboot.

I haven't done any formal performance testing, but it seems like loading all the CRLs takes a couple seconds and the checksum comparison adds a negligible amount of overhead to every CRL validation.

**Review by patricksmithdds — APPROVED** [review]
Changes here look good to me. I think if we see performance issues in the future, we can find a different workaround, but this looks good for now 👍

**Comment by jordangov** [comment]
Yep, I'm good.

**Comment by dandds** [comment]
thanks all!

**Pull request merged**
