### PR TITLE
Login and redirect

### PR DESCRIPTION
**Pull request by dandds**
This is the branch @jgarber and I have been working on for a little while, related to the [AT-AT login story](https://www.pivotaltracker.com/story/show/157813829).

This does a few things:
- Pares the existing code down to just what's necessary for the story. We can pull the templated code back in as necessary. 
- Adds integration tests to confirm the app responds correctly depending on whether a user has authenticated.
- Adds a new CA and server certificates, as well as storing the client pub/priv key for our PIVKey for testing purposes.

On a future PR, we should consider abstracting the way the app checks the SSL configuration. Right now, we expect the NGINX app server to set a key/value in the UWSGI environment for us, but if we put this behind an additional proxy that handles the SSL termination we'd get that info in a request header. It should handle both, I think.

### CODE REVIEW

**Comment by dandds** [comment]
Also, @briandds this still relies on Docker. I know you want it to work on a host machine. I'd be happy to pair with you to get that working. I don't have a firm idea for how we'd handle placing all the certs and keys, but we could figure out.

**Review by jgarberdds — APPROVED** [review]
Very nicely done! Looks like a good, clean app!

**Review by briandds — APPROVED** [review]
Looks great.

**Comment by dandds** [comment]
thanks all!

**Pull request merged**
