### PR TITLE
Implement CRL checking

### PR DESCRIPTION
**Pull request by dandds**
With @jgarber. As the title says, this implements basic CRL checks.

We're relying on a [certificate validation](https://github.com/wbond/certvalidator) package. The more popular [cryptography](https://cryptography.io/en/latest/) package does not have a straightforward way to validate certs.

- Generated a "bad" client cert and a corresponding CRL for blacklisting it.
- Changed the NGINX config to pass the app the "raw" client certificate for validation against the CRLs.
- Updated the `script/setup` to pull the DoD CRLs into a directory so that the app can compile and use them for validation.

### CODE REVIEW

**Review by briandds — CHANGES_REQUESTED** [review]
I ran `script/test` but got failures, e.g.
```
E       assert 500 == 302
E        +  where 500 = <Response [500]>.status_code

test/test_main.py:14: AssertionError
__________________________________________ test_log_in_fails_without_cac ___________________________________________
```

**Comment by dandds** [comment]
@briandds It's having a problem parsing one of the updated CRLs from the DoD. We'll have to look into that more. For now, we're reverting to our rack-space hosted copy.

**Comment by jgarberdds** [comment]
"Bad AT-AT" 😄 
at-at

**Comment by dandds** [comment]
Updated `script/setup` to always refresh CRL zip. There's another [story](https://www.pivotaltracker.com/n/projects/2160940/stories/158161825) for managing the DoD CRLs effectively, since that will be a bit of work in its own right.

I also rolled back Alpine because of some dependency issues. I made another [chore](https://www.pivotaltracker.com/n/projects/2160940/stories/158220571) to resolve those later.

**Comment by briandds** [comment]
Now getting this error when I run `script/test` :
```
Creating network "authnid_default" with the default driver
Creating authnid_backend-tests_1
Creating authnid_backend_1

ERROR: for backend-tests  Cannot start service backend-tests: oci runtime error: container_linux.go:247: starting container process caused "exec: \"bash\": executable file not found in $PATH"

ERROR: Encountered errors while bringing up the project.
``

**Comment by jordangov** [comment]
Is this still a WIP?

**Comment by dandds** [comment]
@jordangov I think @briandds's current errors are caused by stale docker containers. CI is passing, so it should be fine if you want to pull and try it.

**Review by briandds — APPROVED** [review]

**Pull request merged**
